universe_cache: "stock_collector/meta/cache/a_share_list.json"
default_symbols:
  - "SH600000"
  - "SH600004"
  - "SH600009"
  - "SH600010"
  - "SH600011"
  - "SH600015"
  - "SH600016"
  - "SH600018"
  - "SH600019"
  - "SH600020"
  - "SH600028"
  - "SH600029"
  - "SH600030"
  - "SH600031"
  - "SH600036"
  - "SH600048"
  - "SH600050"
  - "SH600061"
  - "SH600089"
  - "SH600104"
  - "SH600111"
  - "SH600115"
  - "SH600150"
  - "SH600176"
  - "SH600196"
  - "SH600219"
  - "SH600276"
  - "SH600309"
  - "SH600340"
  - "SH600346"
  - "SH600372"
  - "SH600406"
  - "SH600436"
  - "SH600438"
  - "SH600519"
  - "SH600547"
  - "SH600570"
  - "SH600585"
  - "SH600588"
  - "SH600606"
  - "SH600660"
  - "SH600690"
  - "SH600703"
  - "SH600760"
  - "SH600887"
  - "SH600900"
  - "SH600919"
  - "SH600938"
  - "SH600941"
  - "SZ000001"
  - "SZ000002"
  - "SZ000063"
  - "SZ000066"
  - "SZ000100"
  - "SZ000157"
  - "SZ000166"
  - "SZ000333"
  - "SZ000338"
  - "SZ000568"
  - "SZ000651"
  - "SZ000725"
  - "SZ000728"
  - "SZ000776"
  - "SZ000858"
  - "SZ000876"
  - "SZ000895"
  - "SZ000938"
  - "SZ000977"
  - "SZ002027"
  - "SZ002049"
  - "SZ002050"
  - "SZ002230"
  - "SZ002415"
  - "SZ002475"
  - "SZ002714"
  - "SZ002812"
  - "SZ002821"
  - "SZ300059"
  - "SZ300122"
  - "SZ300142"
  - "SZ300274"
  - "SZ300308"
  - "SZ300316"
  - "SZ300498"
  - "SZ300750"
  - "SZ300760"
  - "SZ300782"
exclude:
  st: true
  delisted: true
